# Generated by Django 4.1.7 on 2024-05-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srvmedicals', '0002_remove_product_user_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='prescriptions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Dispatch Soon', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvmedicals.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvmedicals.product')),
            ],
        ),
    ]
