# Generated by Django 4.1.7 on 2024-05-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvmedicals', '0003_remove_order_product_order_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
